admin_homepage:
    path:     /Home
    defaults: { _controller: AdminBundle:Default:index }
admin_listPosts:
    path:     /Posts
    defaults: { _controller: AdminBundle:Post:Listposts }
admin_apps:
    path:     /Apps
    defaults: { _controller: AdminBundle:Application:listApps }
Admindelete_apps:
    path:     /Apps/delete{id}
    defaults: { _controller: AdminBundle:Application:delete }
AdminUpdate_apps:
    path:     /Apps/Update{id}
    defaults: { _controller: AdminBundle:Application:Update }

Admin_deletePost:
    path:     /deletepost/{postId}
    defaults: { _controller: AdminBundle:Post:Delete }
Admin_UpdatePost:
    path:     /UpdatePost/{postId}
    defaults: { _controller: AdminBundle:Post:Update }
Admin_DetailPost:
    path:     /DetailPost/{postId}
    defaults: { _controller: AdminBundle:Post:DetailPost }
admin_listComments:
    path:     /Comments
    defaults: { _controller: AdminBundle:Comment:ListComments }
Admin_deleteComment:
    path:     /deletecomment/{commentId}
    defaults: { _controller: AdminBundle:Comment:Delete }
Admin_PaymentsBlogList:
    path:     /paymentBlog
    defaults: { _controller: AdminBundle:AdminBlogProfits:listPayments }
Admin_PaymentsBlogListAccept:
    path:     /AcceptPayment/{id}/{idpayment}
    defaults: { _controller: AdminBundle:AdminBlogProfits:AcceptPayment }
Admin_Redirection:
    path:     /Verify
    defaults: { _controller: AdminBundle:Security:redirect }