admin_homepage:
    path:     /Home
    defaults: { _controller: AdminBundle:Default:index }
admin_listPosts:
    path:     /Posts
    defaults: { _controller: AdminBundle:Post:Listposts }
Admin_deletePost:
    path:     /deletepost/{postId}
    defaults: { _controller: AdminBundle:Post:Delete }
Admin_UpdatePost:
    path:     /UpdatePost/{postId}
    defaults: { _controller: AdminBundle:Post:Update }
Admin_DetailPost:
    path:     /DetailPost/{postId}
    defaults: { _controller: AdminBundle:Post:DetailPost }
admin_listComments:
    path:     /Comments
    defaults: { _controller: AdminBundle:Comment:ListComments }
Admin_deleteComment:
    path:     /deletecomment/{commentId}
    defaults: { _controller: AdminBundle:Comment:Delete }
Admin_PaymentsBlogList:
    path:     /paymentBlog
    defaults: { _controller: AdminBundle:AdminBlogProfits:listPayments }
Admin_PaymentsBlogListAccept:
    path:     /AcceptPayment/{id}/{idpayment}
    defaults: { _controller: AdminBundle:AdminBlogProfits:AcceptPayment }
Admin_Redirection:
    path:     /Verify
    defaults: { _controller: AdminBundle:Security:redirect }
Admin_opportunities:
    path:     /opportunities
    defaults: { _controller: AdminBundle:Opportunity:listopp }
Admin_UpdateOpportunity:
    path:     /Update/{id}
    defaults: { _controller: AdminBundle:Opportunity:Update }
Admin_deleteOpportunity:
    path:     /deleteOpportunity/{id}
    defaults: { _controller: AdminBundle:Opportunity:Delete }