<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRi1vnj6\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRi1vnj6/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerRi1vnj6.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerRi1vnj6\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerRi1vnj6\appProdProjectContainer([
    'container.build_hash' => 'Ri1vnj6',
    'container.build_id' => '69f637cc',
    'container.build_time' => 1554218325,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRi1vnj6');
