<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGyq0zzy\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGyq0zzy/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerGyq0zzy.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerGyq0zzy\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerGyq0zzy\appProdProjectContainer([
    'container.build_hash' => 'Gyq0zzy',
    'container.build_id' => 'afd7d160',
    'container.build_time' => 1552995562,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGyq0zzy');
