<?php

namespace BlogBundle\Repository;

/**
 * PostLikeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogProfitsRepository extends \Doctrine\ORM\EntityRepository
{
}
