<?php

namespace BlogBundle\Repository;

/**
 * PostLikeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostLikeRepository extends \Doctrine\ORM\EntityRepository
{
    public function Suggest($id)
    {
        $dql = $this->createQueryBuilder('blogprofit')->where('blogpost.author='.$id);
        $dql->orderBy('blogpost.postLikesCount', 'DESC');
        $query = $dql->getQuery();
        $query->setMaxResults(10);
        return $query->getResult();
    }

}
