<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSxtqecx\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSxtqecx/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerSxtqecx.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerSxtqecx\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerSxtqecx\appDevDebugProjectContainer([
    'container.build_hash' => 'Sxtqecx',
    'container.build_id' => '09cfb6b5',
    'container.build_time' => 1554242215,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSxtqecx');
