<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4fnt5xg\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4fnt5xg/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container4fnt5xg.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container4fnt5xg\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container4fnt5xg\appDevDebugProjectContainer([
    'container.build_hash' => '4fnt5xg',
    'container.build_id' => 'edfeb24e',
    'container.build_time' => 1554761062,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4fnt5xg');
