<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMxxdbhh\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMxxdbhh/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerMxxdbhh.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerMxxdbhh\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerMxxdbhh\appDevDebugProjectContainer([
    'container.build_hash' => 'Mxxdbhh',
    'container.build_id' => '757ed1e9',
    'container.build_time' => 1554235031,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMxxdbhh');
