<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Contract extends \AppBundle\Entity\Contract implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Contract' . "\0" . 'idContract', '' . "\0" . 'AppBundle\\Entity\\Contract' . "\0" . 'paymentMethod', '' . "\0" . 'AppBundle\\Entity\\Contract' . "\0" . 'startDate', '' . "\0" . 'AppBundle\\Entity\\Contract' . "\0" . 'finishDate', '' . "\0" . 'AppBundle\\Entity\\Contract' . "\0" . 'sum', '' . "\0" . 'AppBundle\\Entity\\Contract' . "\0" . 'prio', '' . "\0" . 'AppBundle\\Entity\\Contract' . "\0" . 'idApplication'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Contract' . "\0" . 'idContract', '' . "\0" . 'AppBundle\\Entity\\Contract' . "\0" . 'paymentMethod', '' . "\0" . 'AppBundle\\Entity\\Contract' . "\0" . 'startDate', '' . "\0" . 'AppBundle\\Entity\\Contract' . "\0" . 'finishDate', '' . "\0" . 'AppBundle\\Entity\\Contract' . "\0" . 'sum', '' . "\0" . 'AppBundle\\Entity\\Contract' . "\0" . 'prio', '' . "\0" . 'AppBundle\\Entity\\Contract' . "\0" . 'idApplication'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Contract $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdContract()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdContract();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdContract', []);

        return parent::getIdContract();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaymentMethod($paymentMethod)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaymentMethod', [$paymentMethod]);

        return parent::setPaymentMethod($paymentMethod);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaymentMethod()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentMethod', []);

        return parent::getPaymentMethod();
    }

    /**
     * {@inheritDoc}
     */
    public function setStartDate($startDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStartDate', [$startDate]);

        return parent::setStartDate($startDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getStartDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStartDate', []);

        return parent::getStartDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setFinishDate($finishDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFinishDate', [$finishDate]);

        return parent::setFinishDate($finishDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getFinishDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFinishDate', []);

        return parent::getFinishDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setSum($sum)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSum', [$sum]);

        return parent::setSum($sum);
    }

    /**
     * {@inheritDoc}
     */
    public function getSum()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSum', []);

        return parent::getSum();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrio($prio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrio', [$prio]);

        return parent::setPrio($prio);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrio', []);

        return parent::getPrio();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdApplication(\AppBundle\Entity\Application $idApplication = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdApplication', [$idApplication]);

        return parent::setIdApplication($idApplication);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdApplication()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdApplication', []);

        return parent::getIdApplication();
    }

}
